import click

from ..login import cluster_call
from ..utils import global_options, ident_filter


@click.group(short_help='info, list',
             epilog='Type "ae5 project sample <command> --help" for help on a specific command.')
@global_options
def sample():
    '''Commands related to sample and template projects.'''
    pass


@sample.command()
@ident_filter('sample')
@global_options
def list(**kwargs):
    '''List the sample projects.
    '''
    cluster_call('sample_list', **kwargs)


@sample.command()
@ident_filter('sample', required=True)
@global_options
def info(**kwargs):
    '''Retrieve the record of a single sample project.

       The SAMPLE identifier must match exactly one name or id of a sample project.
       Wildcards may be included.
    '''
    cluster_call('sample_info', **kwargs)


@sample.command()
@ident_filter('sample', required=True)
@click.option('--name', type=str, required=False, help='Name for the job. If supplied, the name must not be identical to an existing job or run record, unless --make-unique is supplied. If not supplied, a unique name will be autogenerated from the project name.')
@click.option('--make-unique', is_flag=True, default=None, help='If supplied, a counter will be appended to a supplied --name if needed to make it unique.')
@click.option('--tag', default='', help='Commit tag to use for initial revision of project.')
@click.option('--wait', is_flag=True, default=True, help='Wait for the creation session to complete before exiting.')
@global_options
def clone(**kwargs):
    '''Create a copy of a sample or template project.

       The PROJECT identifier must match exactly one name or id of a sample project.
       Wildcards may be included.
    '''
    cluster_call('sample_clone', **kwargs)
